version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=crawler
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crawler
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database", "mysql://root:password@tcp(db:3306)/crawler", "up" ]
    volumes:
      - ./backend/migrations:/migrations
    depends_on:
      - db

volumes:
  db_data:
